### ISSUE TITLE
Coding standards: shorthand syntax for arrays

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/menu_item_visibility#1]
I've noticed in https://github.com/backdrop-contrib/menu_item_visibility/commit/8c85129330b688ec620d8eb000a07281c149621f that you have switched to the short format for arrays. This is only supported in php5.4+, whereas the minimum requirements for Backdrop is php 5.3 (see https://backdropcms.org/requirements). I think we should revert that change.

**Comment by robertgarrigos** [comment]
right. thanks. will do
