### ISSUE TITLE
Restore `conflicts[] = menu_per_role` in the .info file

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/menu_item_visibility#2]
I've noticed that this was removed in https://github.com/backdrop-contrib/menu_item_visibility/commit/8c85129330b688ec620d8eb000a07281c149621f#diff-b291888e86a260338800dad7575c2a18L5 ...I realize that the menu_per_role module has not been ported yet, but this calls for trouble in the future if it does get ported.

**Comment by robertgarrigos** [comment]
yep. Is this conflicts statement being used in backdrop?
